課題7のコードと実行結果
miu-osako/c_practice pull request #10
Opened 2024-08-21 05:57 UTC by miu-osako

プログラムを起動してから呼び出すたびに
1インクリメントした値を返す関数を
作成してください。初期値は0とします。
(intの最大値を超えた場合の動作を
考慮する必要はありません)

関数プロトタイプ
int static_counter();

2024-08-21 06:07 UTC, ShunsukeNakamura2 requested changes

2024-08-21 06:07 UTC, ShunsukeNakamura2 commented on exercise7/practice7.c
> +    static int static_counter()
インデント上げてください

2024-08-21 06:07 UTC, ShunsukeNakamura2 commented on exercise7/result7.txt
> +0
呼び出された回数を返して欲しいので、1回目の呼び出し時には1を返してください

2024-08-21 06:07 UTC, ShunsukeNakamura2 commented on exercise7/practice7.c
> +        printf("%d\n", static_counter());
デバッグがやり辛くなるため、関数の戻り値を直接関数に渡すのは避けてください。

2024-08-21 06:07 UTC, ShunsukeNakamura2 commented on exercise7/practice7.c
> +
細かいですが、ここの改行は不要です

2024-08-22 00:31 UTC, ShotaNagao commented on exercise7/practice7.c
> +    static int static_counter()
自分で定義した関数はコメントで説明を加えて欲しいです。
具体的には関数の働き、引数、戻り値の情報です。
doxygenで調べると書き方が出てくるので参考にしてください。

2024-08-22 00:31 UTC, ShotaNagao commented on exercise7/practice7.c
> +    for(int i = 0; i < 10; i++) {
forの後ろには1文字分スペースを入れてください。
今回は使用されていませんが、if文なども同様です。

2024-08-22 08:52 UTC, miu-osako commented on exercise7/practice7.c
> +    static int static_counter()
インデント上げました

2024-08-22 08:53 UTC, miu-osako commented on exercise7/result7.txt
> +0
counter++ を++counter に変更して、1回目の呼び出し時に1を返すようにしました。

2024-08-22 08:53 UTC, miu-osako commented on exercise7/practice7.c
> +        printf("%d\n", static_counter());
戻り値を間接的に渡すようにしました

2024-08-22 08:53 UTC, miu-osako commented on exercise7/practice7.c
> +
改行を消しました

2024-08-22 08:54 UTC, miu-osako commented on exercise7/practice7.c
> +    static int static_counter()
関数の説明をコメントで加えました。

2024-08-22 08:54 UTC, miu-osako commented on exercise7/practice7.c
> +    for(int i = 0; i < 10; i++) {
forの後ろに半角スペースを入れました

2024-08-22 23:05 UTC, ShunsukeNakamura2 requested changes

2024-08-22 23:05 UTC, ShunsukeNakamura2 commented on exercise7/practice7.c
> + * @remark 演習で指定されているため、この関数名を使用しました。
ソースコードに書くことではない気がします

2024-08-22 23:05 UTC, ShunsukeNakamura2 commented on exercise7/result7.txt
> +0
実行結果が変わったと思うので更新してください

2024-08-23 01:25 UTC, miu-osako commented on exercise7/practice7.c
> + * @remark 演習で指定されているため、この関数名を使用しました。
remark消しました

2024-08-23 01:26 UTC, miu-osako commented on exercise7/result7.txt
> +0
result7.txtもaddします

2024-08-23 01:37 UTC, ShunsukeNakamura2 approved these changes

2024-08-23 04:40 UTC, ShotaNagao approved these changes

2024-08-23 04:58 UTC, merged