課題9のコードと実行結果
miu-osako/c_practice pull request #12
Opened 2024-08-26 07:14 UTC by miu-osako

int型の2つの変数の値を入れ替える
関数を作成してください。

出力例：
void swap_int(int *a, int *b);

2024-08-26 07:22 UTC, ShunsukeNakamura2 requested changes

2024-08-26 07:22 UTC, ShunsukeNakamura2 commented on exercise9/practice9.c
> +void swap_int(int *a, int *b)
プロトタイプ宣言をしてください

2024-08-26 07:22 UTC, ShunsukeNakamura2 commented on exercise9/practice9.c
> +	int u, v;
なぜuとvなんですか？
単純に興味があるだけです。

2024-08-26 07:27 UTC, ShunsukeNakamura2 commented on exercise9/practice9.c
> +void swap_int(int *a, int *b)
関数コメントを作成してください

2024-08-26 08:55 UTC, ShotaNagao commented on exercise9/practice9.c
> +	int tmp;
変数の宣言部分と処理部分の境界なので、改行入れてください。

2024-08-27 02:52 UTC, miu-osako commented on exercise9/practice9.c
> +void swap_int(int *a, int *b)
mainの前にプロトタイプ宣言をしました

2024-08-27 02:52 UTC, miu-osako commented on exercise9/practice9.c
> +	int u, v;
参考にしたサイトがuとvを使っていたからです

2024-08-27 02:53 UTC, miu-osako commented on exercise9/practice9.c
> +void swap_int(int *a, int *b)
関数コメントを書きました

2024-08-27 02:53 UTC, miu-osako commented on exercise9/practice9.c
> +	int tmp;
改行を入れました

2024-08-27 03:01 UTC, ShunsukeNakamura2 commented on exercise9/practice9.c
> +	int u, v;
なるほど、了解です。

2024-08-27 03:02 UTC, ShunsukeNakamura2 approved these changes

2024-08-27 04:38 UTC, ShotaNagao approved these changes

2024-08-27 04:40 UTC, ShotaNagao commented
下記に過去の研修で頂いたコメントで別解をもらっていたのでそちら記載いたします。
目を通しておいてください。

以下過去コメント
【教えてもらったこと】
たまに以下のような書き方をする人がいるので(うちの会社でやると多分レビューで指摘されるけど)覚えておいてください。知らないと面食らうので。

void swap_int(int *n1, int *n2)
{
　if (*n1 == *n2) {
　　return;
　}
　*n1 ^= *n2;
　*n2 ^= *n1;
　*n1 ^= *n2;
}

このやり方は、関数マクロにすることで、引数部分がint以外の場合でも適用できるので好んで使う人たちが世の中にはいます。
ただ、いかんせん読みにくくなるため、うちの会社では推奨されてないです(多分)し、製品コードでは見たことないですね。
関数マクロにすればのところはこんな感じ

#define swap(a, b) ((a) ^= (b); (b) ^= (a); (a) ^= (b);)

こう書くと引数がintでもdoubleでもcharでも構造体でも動きます。
古の黒魔法使いなどはこういう事をしますが、最近はやる人いないと思います。。
XOR交換アルゴリズムは、最近のCPUではこのやり方よりも普通に一時変数を使用した方がコンパイラ最適化によって早くなるので、正直このやり方をやるメリットは今の時代は1つもないみたいです。

2024-08-27 04:43 UTC, merged