課題10のコードと実行結果
miu-osako/c_practice pull request #13
Opened 2024-08-30 02:13 UTC by miu-osako

下記構造体の配列をソートし表示してください。
ソート順は、nの値で昇順、nが同一の値の
場合はsの文字コードで昇順とします。
ソート処理にはC標準関数qsort()を使ってください。

構造体と配列
typedef struct DAT_t {
       int n;
       const char* s;
} DAT;
DAT dat[] = {
       {9, "A"},
       {2, "A"},
       {5, "AB"},
       {5, "AA"},
};

2024-08-30 03:22 UTC, ShunsukeNakamura2 requested changes

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @details int型のnを比較してからchar型のsを比較する関数
この説明だとnとsが何を表しているか分からないので
struct DAT_t のメンバだと分かる説明が欲しいです。

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @return n1がn2より小さい場合は-1を、大きい場合は1を、同じ場合はs1とs2を比較する
n1,n2,s1,s2という変数はこのコード内に無いので、存在するものを使用した説明に書き換えてください。

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +int compare(const void *a, const void *b){
struct DAT_t  を比較していると分かる名前にしてください。

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +int compare(const void *a, const void *b){
プロトタイプ宣言をしてください。

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	DAT *dat2 = (DAT *)b;
dat1, dat2 にもconstを付けると、不意の値の書き換えを防止できます

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @return n1がn2より小さい場合は-1を、大きい場合は1を、同じ場合はs1とs2を比較する
引数についての説明も追加してください

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	if (dat1->n < dat2->n) return -1;
ブロック内が一行であっても、{ } で囲むようにしてください

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	DAT dat[]={
= の左右に空白を入れてください

2024-08-30 03:22 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	size_t numDat = sizeof(dat) / sizeof(dat[0]);
スネークケースで命名してください。

2024-08-30 05:52 UTC, miu-osako commented on exercise10/practice10.c
> + * @details int型のnを比較してからchar型のsを比較する関数
int型のnを、struct DAT_tのint nに、
char型のsを、char* sに変更しました

2024-08-30 06:31 UTC, miu-osako commented on exercise10/practice10.c
> + * @return n1がn2より小さい場合は-1を、大きい場合は1を、同じ場合はs1とs2を比較する
dat1のn, dat2のnに変更しました

2024-08-30 06:31 UTC, miu-osako commented on exercise10/practice10.c
> +int compare(const void *a, const void *b){
compare_DAT_tに変更しました

2024-08-30 06:32 UTC, miu-osako commented on exercise10/practice10.c
> +	DAT *dat2 = (DAT *)b;
constを付けました

2024-08-30 06:33 UTC, miu-osako commented on exercise10/practice10.c
> + * @return n1がn2より小さい場合は-1を、大きい場合は1を、同じ場合はs1とs2を比較する
paramを追加しました

2024-08-30 06:33 UTC, miu-osako commented on exercise10/practice10.c
> +	if (dat1->n < dat2->n) return -1;
｛｝を追加しました

2024-08-30 06:33 UTC, miu-osako commented on exercise10/practice10.c
> +	DAT dat[]={
=の左右にスペースを入れました
もう二度目の指摘なので、次回はないように気を付けます

2024-08-30 06:34 UTC, miu-osako commented on exercise10/practice10.c
> +	size_t numDat = sizeof(dat) / sizeof(dat[0]);
スネークケースで命名しました
こちらも二度目の指摘なので、次回はないように注意いたします

2024-08-30 07:04 UTC, ShunsukeNakamura2 requested changes

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +int compare_DAT_t(const void *a, const void *b){
通常、プロトタイプ宣言をした際の関数定義はmain()の下に書きます

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +int compare_DAT_t(const void *a, const void *b){
{ を改行してください

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	if (dat1->n > dat2->n) {
同じものを連続で比較しているので、else ifにした方が分かりやすいです。

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @param[out] b DATのメンバにアクセスするポインタ2
aとbはoutですか？

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @brief ソート関数
ソート関数ではなく、（ソートのための）比較関数では？

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @return dat1のnがdat2のnより小さい場合は-1を、大きい場合は1を、同じ場合はsを比較する
sを比較して、どうだったら何が返ってきますか？
例えばですが、以下みたいな書き方が考えられます。
```
/**
* @brief ...
* @details ここで大小の判定基準を説明する
* ・・・
* @return aが大きかったら、bが大きかったら、同じなら何が返るかを説明する
*/
```

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @return dat1のnがdat2のnより小さい場合は-1を、大きい場合は1を、同じ場合はsを比較する
dat1, dat2は関数内のローカル変数なので、ここでは引数であるa, bを使用するのが適切です。

2024-08-30 07:04 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @param[out] b DATのメンバにアクセスするポインタ2
aとbのこの関数における役割は、「DATのメンバにアクセスするポインタ」 というよりも
「大小比較の対象」 だと思います。

2024-08-30 09:43 UTC, ShotaNagao commented on exercise10/practice10.c
> +	for (size_t i = 0; i < num_dat; i++) {
武ノ内さんも同様の書き方をしていましたが、それに対しての阿見さんからの指摘です。
ご確認よろしくお願いいたします。

for文の()内の変数宣言は、UNIX系のコンパイラでエラーになる場合があるので、()の外で宣言して下さい。

2024-08-30 09:43 UTC, ShotaNagao commented on exercise10/practice10.c
> +typedef struct DAT_t{
DAT_tの後ろに半角スペースを入れてください。

2024-08-30 09:43 UTC, ShotaNagao commented on exercise10/practice10.c
> +}DAT;
}の後ろに半角スペースを入れてください。

2024-08-30 09:43 UTC, ShotaNagao commented on exercise10/practice10.c
> + * @details struct DAT_tのint nを比較してからchar* sを比較する関数
これ実際の動作は違いますよね
①DAT_tのint nを比較する
ここで処理の分岐
②①の比較の結果同値でない場合はreturn
②’①の比較の結果同値の場合、sを比較
という流れだと思います。

今のままだと行う処理が①→②→②'ように読めますが、実際は
①→②　or　①→②'
だと思います。

2024-09-02 01:43 UTC, miu-osako commented on exercise10/practice10.c
> +int compare_DAT_t(const void *a, const void *b){
プロトタイプ宣言した関数の定義をmain()の下に書きました

2024-09-02 01:43 UTC, miu-osako commented on exercise10/practice10.c
> +int compare_DAT_t(const void *a, const void *b){
{を改行しました

2024-09-02 01:46 UTC, miu-osako commented on exercise10/practice10.c
> +	if (dat1->n > dat2->n) {
else ifにしました

2024-09-02 01:46 UTC, miu-osako commented on exercise10/practice10.c
> + * @param[out] b DATのメンバにアクセスするポインタ2
inでした

2024-09-02 01:47 UTC, miu-osako commented on exercise10/practice10.c
> + * @brief ソート関数
比較関数に変更しました

2024-09-02 03:07 UTC, miu-osako commented on exercise10/practice10.c
> + * @return dat1のnがdat2のnより小さい場合は-1を、大きい場合は1を、同じ場合はsを比較する
引数のaとbを使用しました

2024-09-02 03:08 UTC, miu-osako commented on exercise10/practice10.c
> + * @param[out] b DATのメンバにアクセスするポインタ2
大小比較の対象、に変更しました

2024-09-02 03:09 UTC, miu-osako commented on exercise10/practice10.c
> +	for (size_t i = 0; i < num_dat; i++) {
size_t i;を宣言部分に移しました

2024-09-02 03:10 UTC, miu-osako commented on exercise10/practice10.c
> +typedef struct DAT_t{
DAT_tの後ろに半角スペースを入れました

2024-09-02 03:10 UTC, miu-osako commented on exercise10/practice10.c
> +}DAT;
}の後ろに半角スペースを入れました

2024-09-02 03:23 UTC, miu-osako commented on exercise10/practice10.c
> + * @return dat1のnがdat2のnより小さい場合は-1を、大きい場合は1を、同じ場合はsを比較する
aが大きい場合1、bが大きい場合-1を返し、同値の場合sを比較し、辞書順
に並ぶよう戻り値を返す、と書き換えました

2024-09-02 03:24 UTC, miu-osako commented on exercise10/practice10.c
> + * @details struct DAT_tのint nを比較してからchar* sを比較する関数
struct DAT_tのint nを比較して、同値の場合char* sも比較する関数、と書き換えました

2024-09-02 04:54 UTC, ShotaNagao commented on exercise10/practice10.c
> + * @return aが大きい場合1、bが大きい場合-1を返し、同値の場合sを比較し、辞書順に並ぶよう戻り値を返す
とても細かい指摘ですが、
同値の場合sを比較し、辞書順に並ぶよう戻り値を返す
とありますが、少し違和感があります。

違和感のポイントは下記の2点
1. 辞書順
　これはman page等でstrcmpの仕様を確認してください。何を基準に大小比較しているか記載されています。

2. 並ぶよう戻り値を返す
　qsort関数で使うための関数なのでこの説明になっていると思いますが、この関数自体の動きでソートをしているわけではない気がする。
　この関数自体は、引数a,bの大小関係を比較しているだけ。(a>bの時は正の値、a=bの時は0、a<bの時は負の値を返しているだけ。)
　並び替えるという機能はこの関数の外側で必要があれば説明するで大丈夫だと思います。

2024-09-02 04:54 UTC, ShotaNagao commented on exercise10/practice10.c
> +	}
elseの時の書き方が変です。

2024-09-02 04:54 UTC, ShotaNagao commented on exercise10/practice10.c
> +	else{
ここのelseは必要ですか？

2024-09-02 04:56 UTC, ShunsukeNakamura2 requested changes

2024-09-02 04:56 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> + * @return aが大きい場合1、bが大きい場合-1を返し、同値の場合sを比較し、辞書順に並ぶよう戻り値を返す
@returnでは、大小判定のロジックよりも「実際に何が返ってくるか」を知りたいので、
`@return aが大きい場合1、bが大きい場合-1、同値の場合0を返す`
で良いと思います。

2024-09-02 21:39 UTC, ShunsukeNakamura2 requested changes

2024-09-02 21:39 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	if (dat1->n > dat2->n) {
長尾さんの指摘、こういう意図ではないと思います。
HULFT_Coding_Style.txtの208行目～を読んでください。

2024-09-03 04:53 UTC, ShotaNagao commented on exercise10/practice10.c
> + * @return aが大きい場合1、bが大きい場合-1、同値の場合0を返す
メンバn同士の比較はこの通りですけど、メンバsの比較は本当にこの値で返しますか？
以下man pageからの引用

> 
> 説明
> strcmp() 関数は二つの文字列 s1 と s2 を較べる。 この関数は、 s1 が s2 に較べて 1)小さい、2)等しい、3)大きい場合に、 ゼロよりも 1)小さい、2)等しい、3)大きい整数を返す。
> strncmp() 関数は、s1 と s2 の最初の n バイトだけを比較する ことを除けば、strcmp()と同様である。  
> 
> 返り値
> strcmp() 関数と strncmp() 関数は整数を返す。 この整数は、ゼロよりも、1)小さい、2)等しい、3)大きいのいずれかである。 それぞれは、s1（または、この文字列の最初の n バイト）が s2 よりも、1)小さい、2)等しい、3)大きいに対応している。

2024-09-03 07:29 UTC, ShunsukeNakamura2 requested changes

2024-09-03 07:29 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +	}else if (dat1->n > dat2->n) {
}とelse ifの間に空白を入れてください

2024-09-03 07:29 UTC, ShunsukeNakamura2 commented on exercise10/practice10.c
> +		return strcmp(dat1->s, dat2->s);
インデントは適切にお願いします。

2024-09-04 00:09 UTC, ShotaNagao approved these changes

2024-09-04 00:40 UTC, ShunsukeNakamura2 approved these changes

2024-09-04 04:19 UTC, Ryusei-Ami requested changes
関数コメントの指摘のみです。

2024-09-04 04:19 UTC, Ryusei-Ami commented on exercise10/practice10.c
> + *
好みの問題ではあるのですが、ちょっと空行多くて見づらいので、以下のような感じにして下さい。

@brief
@details

@param
@param

@return

2024-09-04 04:19 UTC, Ryusei-Ami commented on exercise10/practice10.c
> + * @brief 比較関数
@detailsの説明はこっちで良いかと。以下のような感じで。
「struct DAT_tのint nを比較、同値の場合char* sを比較」
@detailsは、細かい説明が必要なときだけで良いです。このレベルの関数ならば不要かと。

2024-09-04 05:42 UTC, Ryusei-Ami approved these changes

2024-09-04 05:44 UTC, merged