課題11のコードと実行結果
miu-osako/c_practice pull request #14
Opened 2024-09-05 02:54 UTC by miu-osako

コマンドラインで指定されたテキストファイルの
内容を表示するプログラムを作成してください。
(文字コード以外のコードが含まれていた
場合のことを考慮する必要はありません)

usage
usage: プログラム名 filename

2024-09-05 03:27 UTC, ShotaNagao commented on exercise11/practice11.c
> +	fclose(file);
fcloseは失敗する可能性があるので、エラー処理を追加してください。

2024-09-05 03:27 UTC, ShotaNagao commented on exercise11/practice11.c
> +	while ((ch = fgetc(file)) != EOF)
一文字ずつ読み込むことは効率が悪い(理由は自分で調べてみてください)ので、fgetsを使用した処理に書き換えてください。

2024-09-05 03:27 UTC, ShotaNagao commented on exercise11/practice11.c
> +	FILE *file = fopen("test.txt", "r");
コマンドラインからファイル名を入力するようにしてください

2024-09-05 06:07 UTC, miu-osako commented on exercise11/practice11.c
> +	while ((ch = fgetc(file)) != EOF)
fgetcをfgetsに書き換えました

2024-09-05 06:07 UTC, miu-osako commented on exercise11/practice11.c
> +	fclose(file);
以下のエラー処理コードを追加いたしました。

if (ferror(file)) {
                printf("ファイル読み込みエラーが発生しました。\n");
        }

2024-09-06 03:37 UTC, miu-osako commented on exercise11/practice11.c
> +	FILE *file = fopen("test.txt", "r");
コマンドラインからファイル名を入力するようにしました

2024-09-06 05:04 UTC, ShotaNagao commented on exercise11/practice11.c
> +		fgets(str, 100, file) == NULL;
これは何をしたい処理ですか？

2024-09-06 05:04 UTC, ShotaNagao commented on exercise11/practice11.c
> +	FILE *file = NULL;
ファイルポインタは通例fpで表されるので、ここでもfpで構いません。

2024-09-06 05:04 UTC, ShotaNagao commented on exercise11/practice11.c
> +	if (ferror(file)) {
printfの内容から察すると、これはクローズの処理のエラー判定だと思いますが、fcloseの前に行っているのはなぜでしょうか？

2024-09-06 05:04 UTC, ShotaNagao commented on exercise11/practice11.c
> +	fclose(file);
エラー処理の場所が違います。
エラー処理は該当の処理を行った後行わないととエラー処理とは言えません。

2024-09-06 05:04 UTC, ShotaNagao commented on exercise11/practice11.c
> +	char str[100];
「100」のような書き方をマジックナンバーと言います。
マジックナンバーは読む人に全く伝わらないため避けた方が良い書き方です。
今回だと「100」は何を意味しているのか、何故この値になっているのか、この値である必要性はあるのか、といったことを読み手が考えることになります。

マクロなどを適宜定義してみてください。

2024-09-06 06:15 UTC, miu-osako commented on exercise11/practice11.c
> +		fgets(str, 100, file) == NULL;
fileから文字列を読み込む処理です。
NULLは削除しました

2024-09-06 06:22 UTC, miu-osako commented on exercise11/practice11.c
> +	FILE *file = NULL;
fileをfpにしました

2024-09-09 02:29 UTC, miu-osako commented on exercise11/practice11.c
> +	fclose(file);
エラー処理を該当箇所の後ろに配置しました

2024-09-09 02:30 UTC, miu-osako commented on exercise11/practice11.c
> +	char str[100];
変数を定義してマジックナンバーを定義しました

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/practice11.c
> +	max_length= 256;
=の前後のスペースを確認してください。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/practice11.c
> +	max_length= 256;
前回と同じ指摘になるのですが、256って何でしょうかとなります。
解決策としてはマクロがあります。
確認してみてください。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/practice11.c
> +	fp = fopen(argv[1], "r");
プログラム使用者が指定する引数(今回だとargvやargc)は直接処理の中で使うのは避けた方がいいです。
infileなどのポインタ変数で一旦受けてそれを使用してください。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/practice11.c
> +		fgets(str, max_length, fp);
関数を使用する際には戻り値の項目も目を通すようにしてください。
今回の場合ですと、fgetsもエラーになる場合があります。

また付随して、fgets時にエラーになってもprintfが実行されますが、エラーになってもprintfを実行したい理由がありますでしょうか。
無ければエラー時にループを抜けるようにするのがいいと思います。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/practice11.c
> +	fclose(fp);
fcloseの戻り値も確認してみてください。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/Makefile
> +# 出力ファイル名
出力ファイルがぱっと見で何を指すのか分かりにくい気がします。

ここにコメントをするなら作成する実行ファイルと明確に記載した方がいいと思います。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/Makefile
> +OUTPUT = display_file
実行ファイルとするならPROGRAMがいいかと思います。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/Makefile
> +	rm -f $(OUTPUT)
今回はプログラムが簡潔なため、ソースファイルと実行ファイルが1対1対応しているので、この書き方でも問題なく対象を削除できます。

ただ、ソースファイルと実行ファイルが1対1対応するとは限りません。
汎用的なソースファイルを作成すれば、いくつかの実行ファイルで共有されますし、1つの実行ファイルのために複数のソースファイルが必要になることもあります。
そういったときはオブジェクトファイル(.o)を明示的に作成します。
今回はオブジェクトファイルであっても削除できる形で書いて欲しいです。

2024-09-09 06:45 UTC, ShotaNagao commented on exercise11/Makefile
> +SOURCES = practice11.c
オブジェクトファイル(.o)から実行ファイルを作成するような書き方にしてください。

2024-09-10 00:55 UTC, miu-osako commented on exercise11/practice11.c
> +	max_length= 256;
#define で定義しました

2024-09-10 01:00 UTC, miu-osako commented on exercise11/practice11.c
> +	fp = fopen(argv[1], "r");
ポインタ変数infileに代入しました

2024-09-10 01:41 UTC, miu-osako commented on exercise11/practice11.c
> +		fgets(str, max_length, fp);
fgetsエラー時にループを抜けるようにしました

2024-09-10 01:41 UTC, miu-osako commented on exercise11/practice11.c
> +	fclose(fp);
fcloseの戻り値も設定しました

2024-09-10 01:53 UTC, miu-osako commented on exercise11/Makefile
> +# 出力ファイル名
出力ファイルを作成する実行ファイルに変更しました

2024-09-10 01:53 UTC, miu-osako commented on exercise11/Makefile
> +OUTPUT = display_file
OUTPUTをPROGRAMに変更しました

2024-09-10 05:18 UTC, miu-osako commented on exercise11/Makefile
> +	rm -f $(OUTPUT)
オブジェクトファイルを削除できるよう変更しました

2024-09-10 05:18 UTC, miu-osako commented on exercise11/Makefile
> +SOURCES = practice11.c
オブジェクトファイル(.o)から実行ファイルを作成できるよう変更しました

2024-09-10 05:27 UTC, ShunsukeNakamura2 requested changes

2024-09-10 05:27 UTC, ShunsukeNakamura2 commented on exercise11/Makefile
> +	rm -f practice11.o $(PROGRAM) $(OBJS)
「practice11.o」と「$(OBJS)」は同じものでは？

2024-09-10 05:27 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	infile = argv[1];
argvの中身を参照する前に、argcのチェックをしてください

2024-09-10 05:27 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	FILE *fp = NULL;
宣言の位置どこでしたっけ

2024-09-10 05:27 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		fclose(fp);
ファイルクローズやメモリ解放等の終了前処理が散らばるのは好ましくないので、34行目のfclose()とまとめてください

2024-09-10 05:27 UTC, ShunsukeNakamura2 commented on exercise11/result11.txt
> +[osako@vzr93001 exercise11]$ ./display_file test.txt
細かいですが、
$ make
と書いてるので、ここも合わせて
$ ./display_file test.txt
と書くのが適切だと思います

2024-09-10 06:00 UTC, miu-osako commented on exercise11/Makefile
> +	rm -f practice11.o $(PROGRAM) $(OBJS)
同じものです

2024-09-10 07:23 UTC, miu-osako commented on exercise11/practice11.c
> +	FILE *fp = NULL;
改行を消しました

2024-09-10 07:23 UTC, miu-osako commented on exercise11/practice11.c
> +	infile = argv[1];
argv参照の前にargcのチェックをしました

2024-09-10 08:25 UTC, miu-osako commented on exercise11/result11.txt
> +[osako@vzr93001 exercise11]$ ./display_file test.txt
[osako@vzr93001 exercise11]の部分を消しました

2024-09-11 23:07 UTC, ShunsukeNakamura2 requested changes

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	while (fgets(str, READ_FILE_MAX + 1, fp) != NULL) {
fgets()の第2引数はstrの大きさが変更になっても手を加えなくて済むような記述にすると保守性が上がります

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	if (!feof(fp)) {
!feof(fp) ：EOFでない時
でも正しく判定できますが、
ferror(fp) ：エラーの時
の方が直感的に読みやすいと思います

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		return 1;
リターン値を0,1としていますが、「成功」「失敗」が一目でわかるように
defineで定義してください

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		perror("error opening file\n");
fopen()に失敗した場合の出力結果をここの返信で教えてください

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		printf("usage: display_file filename\n");
エラーメッセージは「標準エラー出力」に出力してください

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	if (fclose(fp) != 0) {
このように書いてしまうと、デバッグやテスト時に、
「変数に任意の値を設定してifの中に入る」
ということができなくなります

2024-09-11 23:07 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +	char str[READ_FILE_MAX + 1];
@ShotaNagao 
自分はここの+1は不要と思うのですがどうでしょうか

2024-09-12 00:46 UTC, ShotaNagao commented on exercise11/practice11.c
> +	char str[READ_FILE_MAX + 1];
不要だと思うので、+1はしないでいいです。

2024-09-12 00:46 UTC, ShotaNagao commented on exercise11/practice11.c
> +	int rc = 0;
この変数の役割が、main関数の戻り値になるだと思いますが、戻り値に1がべた書きされている箇所が多いと思います。
returnはrcで行うに統一してください。

2024-09-12 02:55 UTC, miu-osako commented on exercise11/practice11.c
> +		perror("error opening file\n");
error reading file
: Success

2024-09-12 02:56 UTC, miu-osako commented on exercise11/practice11.c
> +	if (!feof(fp)) {
ferror(fp) ：に書き換えました

2024-09-12 03:20 UTC, miu-osako commented on exercise11/practice11.c
> +	while (fgets(str, READ_FILE_MAX + 1, fp) != NULL) {
第2引数をsizeof(str)にしました

2024-09-12 03:25 UTC, miu-osako commented on exercise11/practice11.c
> +		return 1;
#define SUCCESS 0 /*正常終了*/
#define FAILURE 1 /*異常終了*/
定義しました

2024-09-12 03:30 UTC, miu-osako commented on exercise11/practice11.c
> +		printf("usage: display_file filename\n");
stderrに書き換えました

2024-09-12 04:35 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		perror("error opening file\n");
これ成功してるので、失敗時を教えてください
ファイルオープンに失敗すればいいので、コマンドライン引数に「存在しないファイル名」や「存在してるけどこれはディレクトリ」を渡すと良いと思います

2024-09-12 05:14 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		return 1;
ありがとうございます。
この様に一か所にまとめておくと、「やっぱり失敗時のreturn は-1にしよう」
のような仕様変更が入っても、修正が少なく済みます

2024-09-12 05:22 UTC, miu-osako commented on exercise11/practice11.c
> +		perror("error opening file\n");
失礼いたしました
error opening file
: No such file or directory

2024-09-12 05:31 UTC, ShunsukeNakamura2 requested changes

2024-09-12 05:31 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		perror("error opening file\n");
ありがとうございます。
ちなみに、ディレクトリを渡すと、
error reading file
: Is a directory
となります。何が言いたいかというと、ファイル名が書かれる前提のメッセージが準備されているので、ファイル名も一緒に表示させてください。
仮に複数ファイルを使うプログラムだった時に、どのファイル？となるのでファイル名は分かった方が良いです。

2024-09-12 05:31 UTC, ShotaNagao commented on exercise11/practice11.c
> +	int rc = 0;
returnにマクロで定義する戻り値を書く方針になったため、rcで統一する必要はなくなりました。

2024-09-12 05:31 UTC, ShotaNagao commented on exercise11/practice11.c
> +	int chk;
変数名が少しアバウトだと思います。
fcloseの戻り値を保存する変数なので、file_close_statusやclose_result、close_retなどもう少し具体的な名前にした方が良いと思います。

2024-09-12 05:40 UTC, ShunsukeNakamura2 commented on exercise11/practice11.c
> +		perror("error opening file\n");
ファイル名が書かれる前提のメッセージは言い過ぎでした。
いずれにせよファイル名が分かった方がユーザに親切なので、対応お願いします。

2024-09-12 05:41 UTC, miu-osako commented on exercise11/practice11.c
> +	int chk;
file_close_statusに変更しました

2024-09-12 07:39 UTC, ShotaNagao approved these changes

2024-09-12 07:40 UTC, ShunsukeNakamura2 approved these changes

2024-09-12 08:08 UTC, Ryusei-Ami requested changes

2024-09-12 08:08 UTC, Ryusei-Ami commented on exercise11/practice11.c
> +	int rc = 0;
マクロを定義しているだから、マクロを使うべきでは？

2024-09-12 08:08 UTC, Ryusei-Ami commented on exercise11/practice11.c
> +#define READ_FILE_MAX 256 /*ファイル読み込み最大バイト数を定義*/
256に特に意味が無いようでしたら、ファイルI/Oサイズはページサイズにして下さい。

2024-09-13 03:16 UTC, miu-osako commented on exercise11/practice11.c
> +#define READ_FILE_MAX 256 /*ファイル読み込み最大バイト数を定義*/
8192バイトに書き換えました

2024-09-13 03:17 UTC, miu-osako commented on exercise11/practice11.c
> +	int rc = 0;
0の代わりにSUCCESSに書き換えました

2024-09-13 04:45 UTC, Ryusei-Ami approved these changes

2024-09-13 05:02 UTC, merged