課題12のコードと実行結果
miu-osako/c_practice pull request #15
Opened 2024-09-24 08:27 UTC by miu-osako

パラメータで渡されたファイルの16進ダンプを
表示するプログラムを作成してください。

usage
usage: プログラム名 filename
options: filename ファイル名

出力例：
$ ADDRESS 00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
$ 00000000 01 02 03 41 42 43 20 5C 26 82 A0 83 41 B1 B2 82
$ 00000100 A2

2024-09-24 09:10 UTC, ShunsukeNakamura2 requested changes

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +#define BYTES_HEX 16 /*16進数表記*/
名前とコメント、これが適切かもう一度検討をお願いします。

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		perror("error opening file\n");
openに失敗したファイル名も、エラーメッセージに書いてください

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +	if (ferror(fp)) {
fread()の失敗時の戻り値を確認してください。
現状だと、失敗してもこのifの中に入らない場合がある気がします。

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		printf("\n");
31行目から38行目までのprintf()を一回のprintf()にまとめてください

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +	fclose(fp);
fclose()のエラーハンドリングを追加してください。

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		return FAILURE;
return前にファイルを閉じてください

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +0000000023 69 6E 63 6C 75 64 65 20 3C 73 74 64 69 6F 2E
ヘッダー行を追加してください

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +0000000023 69 6E 63 6C 75 64 65 20 3C 73 74 64 69 6F 2E
0000000023  ←ここ23の前にスペースが必要です

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		for (i = read_size; i < BYTES_HEX; i++) {
ここは何のためのループです？
printf(" ");
も出力結果に反映されている感じがしないのですが

2024-09-24 09:10 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		address += read_size;
ここは固定で +16 なのでは？

2024-09-25 00:35 UTC, ShotaNagao commented on exercise12/practice12.c
> +	unsigned char bytes[BYTES_HEX];
ファイルのデータを格納している変数なので、それ分かる名前を付けてください。
input_xxxみたいな名前だと分かりやすいかと思います。

2024-09-25 00:35 UTC, ShotaNagao commented on exercise12/practice12.c
> +	unsigned long address = 0;
addressというよりindexが正しいかと思います。
配列のインデックスで検索するとイメージつかめるかと思います。

2024-09-25 04:17 UTC, miu-osako commented on exercise12/practice12.c
> +#define BYTES_HEX 16 /*16進数表記*/
MAX_BYTESに変更しました

2024-09-25 04:26 UTC, miu-osako commented on exercise12/practice12.c
> +		perror("error opening file\n");
ファイル名も含めました

2024-09-25 08:43 UTC, miu-osako commented on exercise12/practice12.c
> +	unsigned char bytes[BYTES_HEX];
input_byteに変更しました

2024-09-26 05:45 UTC, miu-osako commented on exercise12/practice12.c
> +		address += read_size;
read_size を MAX_BYTES に変更しました

2024-09-26 06:05 UTC, miu-osako commented on exercise12/practice12.c
> +		return FAILURE;
43行目と44行目の間にfclose(fp);を追加しました

2024-09-26 07:04 UTC, miu-osako commented on exercise12/practice12.c
> +	if (ferror(fp)) {
fread()の戻り値が失敗したときにferror()に入るよう書き換えました

2024-09-26 07:27 UTC, miu-osako commented on exercise12/practice12.c
> +	fclose(fp);
fclose()のエラーハンドリングを追加しました

2024-09-26 07:27 UTC, miu-osako commented on exercise12/result.txt
> +0000000023 69 6E 63 6C 75 64 65 20 3C 73 74 64 69 6F 2E
ヘッダー行を追加しました

2024-09-26 07:27 UTC, miu-osako commented on exercise12/result.txt
> +0000000023 69 6E 63 6C 75 64 65 20 3C 73 74 64 69 6F 2E
スペースを追加しました

2024-09-26 07:27 UTC, miu-osako commented on exercise12/practice12.c
> +		for (i = read_size; i < BYTES_HEX; i++) {
消しました

2024-09-26 07:28 UTC, miu-osako commented on exercise12/practice12.c
> +	unsigned long address = 0;
address を index に変更しました

2024-09-27 04:26 UTC, ShunsukeNakamura2 requested changes

2024-09-27 04:26 UTC, ShunsukeNakamura2 commented on exercise12/Makefile
> +PROGRAM = a.out
せっかくなので何か名前を付けてください

2024-09-27 04:26 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +000000f0 0A 09 75 6E 73 69 67 6E 65 64 20 63 68 61 72 20
```
000000a0
000000b0
000000c0
000000d0
000000e0
000000f0
```
a～fですが、問題文の出力例からは判別できませんが、ヘッダー行が大文字なので合わせて大文字にしてください

2024-09-27 04:26 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +		fprintf(stderr, "usage: %s filename\n"
これだと
`usage: ./a.out filename`
と./が入りますよね。

2024-09-27 04:36 UTC, ShotaNagao commented on exercise12/practice12.c
> +			sprintf(out + i * 3, " %02X", input_byte[i]);
少し複雑な処理をしているので、実例など出しながらコメントで説明を追記して欲しいです。

2024-09-27 06:40 UTC, miu-osako commented on exercise12/Makefile
> +PROGRAM = a.out
a.out を hexdump に変更しました

2024-09-27 07:29 UTC, miu-osako commented on exercise12/result.txt
> +000000f0 0A 09 75 6E 73 69 67 6E 65 64 20 63 68 61 72 20
%07lx0 を %07lX0 に変更して大文字にしました

2024-09-27 07:32 UTC, miu-osako commented on exercise12/practice12.c
> +		fprintf(stderr, "usage: %s filename\n"
プログラム名 hexdump をベタ打ちしました

2024-09-27 08:46 UTC, miu-osako commented on exercise12/practice12.c
> +			sprintf(out + i * 3, " %02X", input_byte[i]);
コメントで説明を追記しました

2024-09-27 08:48 UTC, ShotaNagao approved these changes

2024-09-27 08:59 UTC, ShunsukeNakamura2 requested changes

2024-09-27 08:59 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +000000f0 0A 09 75 6E 73 69 67 6E 65 64 20 63 68 61 72 20
出力結果更新してください

2024-09-27 09:27 UTC, ShunsukeNakamura2 requested changes

2024-09-27 09:27 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
こっち古い出力結果だと思うので消してもらえますか？

2024-09-27 09:27 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
> +[osako@vzr93001 exercise12]$ ./hexdump practice12.c
[osako@vzr93001 exercise12]  ← これあり、なしどちらでもいいのですが、どちらかに統一しましょうか。

2024-09-27 09:27 UTC, ShunsukeNakamura2 commented on exercise12/result.txt
xxdが消えましたね。
もう一回落ち着いて確認をお願いします。

2024-09-29 23:13 UTC, ShunsukeNakamura2 requested changes

2024-09-29 23:13 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +	/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、半角スペースの1バイトの合計3バイトを使う。最後にNULL文字が入るため、+1している。 */
長いので改行を入れてください
44行目も同様です

2024-09-29 23:13 UTC, ShunsukeNakamura2 commented on exercise12/practice12.c
> +			perror("fread error");
ここは改行があった方が、他のエラーメッセージと揃った表示になると思います

2024-09-30 01:04 UTC, miu-osako commented on exercise12/result.txt
> +ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
消しました

2024-09-30 01:05 UTC, miu-osako commented on exercise12/practice12.c
> +	/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、半角スペースの1バイトの合計3バイトを使う。最後にNULL文字が入るため、+1している。 */
改行入れました

2024-09-30 01:05 UTC, miu-osako commented on exercise12/practice12.c
> +			perror("fread error");
改行（\n）入れました

2024-09-30 01:09 UTC, miu-osako commented on exercise12/result.txt
xxd追加しました、異常系も追加しました

2024-09-30 01:09 UTC, miu-osako commented on exercise12/result.txt
> +[osako@vzr93001 exercise12]$ ./hexdump practice12.c
なしにします

2024-09-30 01:21 UTC, ShunsukeNakamura2 approved these changes

2024-09-30 01:43 UTC, Ryusei-Ami requested changes
ロジックには問題ないのですが、main()だけで完結させるには処理量が多いので関数化お願いします。

2024-09-30 01:43 UTC, Ryusei-Ami commented on exercise12/practice12.c
> +	/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、
2行以上になるコメントは以下のように記載してください。
類似も同様です。
```
/* 
 * 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、
 * 半角スペースの1バイトの合計3バイトを使う。最後にNULL文字が入るため、+1している。 
 */
```

2024-09-30 01:43 UTC, Ryusei-Ami commented on exercise12/practice12.c
> +	printf("ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F\n");
main()に処理を詰め込みすぎているので、L36-52は関数化しましょう。

2024-09-30 05:40 UTC, miu-osako commented on exercise12/practice12.c
> +	/* 入力文字1文字につき、HEX表記の下2桁(0xXXのXX)を使用するため2 バイト、
コメントの書式を上記のように修正しました

2024-09-30 05:41 UTC, miu-osako commented on exercise12/practice12.c
> +	printf("ADDRESS  00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F\n");
関数化しました

2024-09-30 05:58 UTC, Ryusei-Ami requested changes
関数コメントの指摘のみです。

2024-09-30 05:58 UTC, Ryusei-Ami commented on exercise12/practice12.c
> + * @param[in] file ポインタファイルを読み込む
@paramは引数の説明なので、名詞で終わるほうが自然です。
例：読み込みファイルのファイルポインタ

2024-09-30 07:45 UTC, Ryusei-Ami approved these changes
修正内容について問題ないことを確認しました。
C言語研修、お疲れ様でした。

2024-09-30 07:50 UTC, merged