課題3のコードと実行結果
miu-osako/c_practice pull request #6
Opened 2024-08-08 08:32 UTC by miu-osako

2024-08-08 08:50 UTC, ShunsukeNakamura2 requested changes

2024-08-08 08:50 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +int main() {
引数を設定してください

2024-08-08 08:50 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +int main() {
関数定義の { は次の行に置いてください

2024-08-08 08:50 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +    scanf("%s", str);
scanf()は非推奨なのでscanf_s()を使用してください
もしくは、課題意図としては、標準入力からではなくプログラム内に直書きを想定していたので
char str[]="文字列";
でもいいです

2024-08-08 08:50 UTC, ShunsukeNakamura2 commented on exercise3/result3.txt
> +配列サイズ=22 文字列長=21
標準入力から文字列を入れるのであれば、何の文字列を入れたか分かるように、コマンドの実行、文字列入力、出力の流れをこのファイルに貼って欲しいです

2024-08-08 08:51 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +}
最後、改行を入れてください

2024-08-08 08:53 UTC, ShotaNagao commented on exercise3/practice3.c
> +    scanf("%s", str);
画面からの入力を指定する場合、不正値が入力されることを考慮したコーディングにする必要があります。
不正値の例として
・22文字を超える文字が入力される
・漢字、ひらがななどのマルチバイトの文字が入力される
などがあります。
不正値の入力を許さない場合、例えば画面に入力制限の案内を表示するとか、入力後、値の正誤判定を行う必要が出ます。
ですので、発想の転換として、画面から入力しないという事を考えてみてください。
例えば、strの宣言時に最後の\0以外をaを入れてみて動作を見てみるといいかと思います。

2024-08-08 08:53 UTC, ShotaNagao commented on exercise3/practice3.c
> +    char str[22];
変数の宣言部分と実際の処理には1行空けて欲しいです。

2024-08-08 08:53 UTC, ShotaNagao commented on exercise3/practice3.c
> +}
一般的にファイルの最後は空行になります。
ですので空行を入れてください。

2024-08-08 08:53 UTC, ShotaNagao commented on exercise3/practice3.c
> +int main() {
{
の位置を見直してみてください。

2024-08-12 23:39 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +    scanf("%s", str);
> scanf()は非推奨なのでscanf_s()を使用してください

これについてですが、scanf_s関数はMicrosoftが独自に実装している関数なのでMicrosoftが提供しているコンパイラや環境でないと使用できないです（昨日知りました）
現在はMinGWのgccを使用しているので使えるみたいですが、Linuxのgccではコンパイルが通らないはずです。
プラットフォームに依存しないプログラムを書くのであればfgets()等を使用してください(もちろん今回はプログラムにべた書きでも良いです)
参考までに

2024-08-13 06:16 UTC, miu-osako commented on exercise3/practice3.c
> +int main() {
引数をvoidに設定しました

2024-08-13 06:17 UTC, miu-osako commented on exercise3/practice3.c
> +int main() {
{を次の行に置きました

2024-08-13 06:17 UTC, miu-osako commented on exercise3/practice3.c
> +    scanf("%s", str);
べた書きに修正しました

2024-08-13 06:17 UTC, miu-osako commented on exercise3/practice3.c
> +}
最後改行を入れました

2024-08-13 06:18 UTC, miu-osako commented on exercise3/practice3.c
> +    char str[22];
変数の宣言部分と実際の処理部分の間に改行を入れました

2024-08-13 06:18 UTC, miu-osako commented on exercise3/practice3.c
> +int main() {
改行を入れました

2024-08-13 06:18 UTC, miu-osako commented on exercise3/practice3.c
> +}
改行を入れました

2024-08-13 06:33 UTC, ShunsukeNakamura2 requested changes

2024-08-13 06:33 UTC, ShunsukeNakamura2 commented on exercise3/practice3.c
> +    printf("1文字目は%c、最後の文字は%cです。\n", str[0], str[20]);
任意の長さの文字列に対応できるようにしてください

2024-08-13 08:11 UTC, ShotaNagao commented on exercise3/practice3.c
> +    printf("1文字目は%c、最後の文字は%cです。\n", str[0], str[20]);
個人的にprintfは1回でいいのではないかと思うのですが2回実施している理由はありますでしょうか。
改行があるからとか、引数が多くなりそうだからなどでしょうか。

2024-08-14 01:32 UTC, miu-osako commented on exercise3/practice3.c
> +    printf("1文字目は%c、最後の文字は%cです。\n", str[0], str[20]);
printfを1回にしました。
改行があるからという理由で2回使っていました。

2024-08-14 01:33 UTC, miu-osako commented on exercise3/practice3.c
> +    printf("1文字目は%c、最後の文字は%cです。\n", str[0], str[20]);
str[20]の部分を、str[strlen(str) - 1]に修正し、任意の長さの文字列に対応できるようにしました。

2024-08-14 01:48 UTC, ShunsukeNakamura2 approved these changes

2024-08-14 02:20 UTC, ShotaNagao approved these changes

2024-08-14 02:22 UTC, merged