課題6のコードと実行結果
miu-osako/c_practice pull request #9
Opened 2024-08-19 07:39 UTC by miu-osako

下記の構造体のサイズ、各メンバの
サイズの合計、各メンバの先頭からの
オフセットとサイズを表示してください。

構造体
 struct SAMPLE_t
{
       char m1;
       short m2;
       char m3;
       long m4;
       char m5;
       void* m6;
};

出力例：
$ 構造体のサイズ=20 メンバの合計サイズ=13
$ char m1 オフセット= 0 サイズ=1
$ short m2 オフセット= 2 サイズ=2
$ char m3 オフセット= 4 サイズ=1
$ long m4 オフセット= 8 サイズ=4
$ char m5 オフセット=12 サイズ=1
$ void* m6 オフセット=16 サイズ=4

2024-08-19 07:49 UTC, ShunsukeNakamura2 commented on exercise6/practice6.c
> +}a;
このaが何か自分で説明できます？

2024-08-19 07:49 UTC, ShunsukeNakamura2 commented on exercise6/practice6.c
> +{
ここの { は改行必要ないですが、問題文（仕様書）に合わせてもらった形だと思うので、今回はOKです。

2024-08-19 07:49 UTC, ShunsukeNakamura2 commented on exercise6/practice6.c
> +    a;
この行は無くても動くはずです

2024-08-20 01:50 UTC, ShunsukeNakamura2 requested changes

2024-08-20 01:50 UTC, ShunsukeNakamura2 commented on exercise6/practice6.c
> +    struct SAMPLE_t a;
struct SAMPLE_t 型の変数と察せられるような変数名にしてください
sampleとか

2024-08-20 04:56 UTC, ShunsukeNakamura2 approved these changes

2024-08-20 04:56 UTC, ShunsukeNakamura2 commented on exercise6/practice6.c
> +           sizeof(sample.m1)+sizeof(sample.m2)+sizeof(sample.m3)+sizeof(sample.m4)+sizeof(sample.m5)+sizeof(sample.m6),
120文字とちょっと長いので、2行に分割した方がよいです。
+の左右にスペースを入れてほしいです。
という指摘がありますが、細かいことなので今回はOKとします(長尾さんが直してと言ったら直してください)。

2024-08-20 05:21 UTC, ShotaNagao commented on exercise6/practice6.c
> +           sizeof(sample.m1)+sizeof(sample.m2)+sizeof(sample.m3)+sizeof(sample.m4)+sizeof(sample.m5)+sizeof(sample.m6),
直すほどでもないので大丈夫です。

2024-08-20 05:21 UTC, ShotaNagao approved these changes

2024-08-20 05:22 UTC, merged